import { ethers, network } from "hardhat";
import fs from "node:fs";
import path from "node:path";
// @ts-ignore - circomlibjs ships no types
import { poseidonContract } from "circomlibjs";

// Deploys the full VEIL stack and writes deployments/<network>.json.
// On a real network you would pass an existing USDC address instead of MockERC20
// and a real DEX router instead of MockSwapRouter.
const LEVELS = 20;
const PROTOCOL_FEE_BPS = 10; // 0.10%

async function main() {
  const [deployer] = await ethers.getSigners();
  console.log(`network: ${network.name}`);
  console.log(`deployer: ${deployer.address}`);

  // Poseidon(2) hasher from circomlib-generated bytecode.
  const hasher = await new ethers.ContractFactory(
    poseidonContract.generateABI(2),
    poseidonContract.createCode(2),
    deployer
  ).deploy();
  await hasher.waitForDeployment();

  // Prefer the real Groth16 verifier if it has been generated; else the mock.
  let verifierName = "MockVerifier";
  try {
    await ethers.getContractFactory("Groth16Verifier");
    verifierName = "Groth16Verifier";
  } catch {
    /* Verifier.sol not built — fall back to MockVerifier */
  }
  const verifier = await (await ethers.getContractFactory(verifierName)).deploy();
  await verifier.waitForDeployment();

  const usdc = await (await ethers.getContractFactory("MockERC20")).deploy();
  const veil = await (await ethers.getContractFactory("VeilToken")).deploy(deployer.address);

  const router = await (await ethers.getContractFactory("MockSwapRouter")).deploy(
    2_000_000_000_000n,
    1n
  );
  await (await veil.transfer(await router.getAddress(), ethers.parseEther("1000000"))).wait();

  const burner = await (await ethers.getContractFactory("BuybackBurner")).deploy(
    await usdc.getAddress(),
    await veil.getAddress(),
    await router.getAddress(),
    deployer.address, // treasury / insurance fund
    5000, // 50% burn
    deployer.address // governance
  );

  const staking = await (await ethers.getContractFactory("VeilStaking")).deploy(
    await veil.getAddress(),
    deployer.address, // governance / slasher
    deployer.address, // slash beneficiary (insurance)
    3 * 24 * 3600, // 3-day unstake cooldown
    ethers.parseEther("10000") // min stake
  );

  const asp = await (await ethers.getContractFactory("AssociationSetRegistry")).deploy(
    deployer.address // ASP operator
  );

  const pool = await (await ethers.getContractFactory("VeilPool")).deploy(
    LEVELS,
    await hasher.getAddress(),
    await verifier.getAddress(),
    await asp.getAddress(),
    await usdc.getAddress(),
    PROTOCOL_FEE_BPS,
    await burner.getAddress(), // protocol fees -> buyback & burn
    deployer.address // governance
  );

  const oracle = await (await ethers.getContractFactory("MockSettlementOracle")).deploy();
  const origin = await (await ethers.getContractFactory("OriginSettler")).deploy(
    await usdc.getAddress(),
    await oracle.getAddress()
  );
  const dest = await (await ethers.getContractFactory("DestinationSettler")).deploy(
    await oracle.getAddress()
  );

  const contracts = {
    poseidonHasher: await hasher.getAddress(),
    verifier: await verifier.getAddress(),
    usdc: await usdc.getAddress(),
    veilToken: await veil.getAddress(),
    swapRouter: await router.getAddress(),
    buybackBurner: await burner.getAddress(),
    staking: await staking.getAddress(),
    associationSetRegistry: await asp.getAddress(),
    pool: await pool.getAddress(),
    settlementOracle: await oracle.getAddress(),
    originSettler: await origin.getAddress(),
    destinationSettler: await dest.getAddress(),
  };

  const deployment = {
    network: network.name,
    deployer: deployer.address,
    verifier: verifierName,
    protocolFeeBps: PROTOCOL_FEE_BPS,
    levels: LEVELS,
    contracts,
  };

  const dir = path.join(__dirname, "..", "..", "..", "deployments");
  fs.mkdirSync(dir, { recursive: true });
  const file = path.join(dir, `${network.name}.json`);
  fs.writeFileSync(file, JSON.stringify(deployment, null, 2) + "\n");

  console.log(`verifier: ${verifierName}`);
  console.log(`wrote ${file}`);
  console.log(JSON.stringify(contracts, null, 2));
}

main().catch((e) => {
  console.error(e);
  process.exit(1);
});
