import { expect } from "chai";
import { ethers } from "hardhat";
// @ts-ignore - circomlibjs ships no types
import { buildPoseidon, poseidonContract } from "circomlibjs";

const LEVELS = 20;
const FIELD =
  21888242871839275222246405745257275088548364400416034343698204186575808495617n;
const ZERO_VALUE =
  20508465343459127713437550997885324284262230915342444940761755190926324417049n;

// Minimal JS mirror of MerkleTreeWithHistory, used to cross-check the on-chain
// root after a deposit (validates the Solidity incremental-tree implementation).
function jsRootAfterFirstLeaf(poseidon: any, leaf: bigint): bigint {
  const F = poseidon.F;
  const h2 = (a: bigint, b: bigint) => F.toObject(poseidon([a, b]));
  const zeros: bigint[] = [ZERO_VALUE];
  for (let i = 1; i < LEVELS; i++) zeros.push(h2(zeros[i - 1], zeros[i - 1]));
  // leaf inserted at index 0 → always the left child, sibling is zeros[i]
  let cur = leaf;
  for (let i = 0; i < LEVELS; i++) cur = h2(cur, zeros[i]);
  return cur;
}

describe("VeilPool", () => {
  async function deploy() {
    const [deployer, alice, recipient, relayer, feeCollector, aspOperator] =
      await ethers.getSigners();

    const poseidon = await buildPoseidon();
    const F = poseidon.F;

    // Deploy the on-chain Poseidon(2) from circomlib-generated bytecode.
    const abi = poseidonContract.generateABI(2);
    const bytecode = poseidonContract.createCode(2);
    const HasherFactory = new ethers.ContractFactory(abi, bytecode, deployer);
    const hasher = await HasherFactory.deploy();
    await hasher.waitForDeployment();

    const Verifier = await ethers.getContractFactory("MockVerifier");
    const verifier = await Verifier.deploy();

    const Token = await ethers.getContractFactory("MockERC20");
    const token = await Token.deploy();

    const ASP = await ethers.getContractFactory("AssociationSetRegistry");
    const asp = await ASP.deploy(aspOperator.address);

    const Pool = await ethers.getContractFactory("VeilPool");
    const protocolFeeBps = 10; // 0.10%
    const pool = await Pool.deploy(
      LEVELS,
      await hasher.getAddress(),
      await verifier.getAddress(),
      await asp.getAddress(),
      await token.getAddress(),
      protocolFeeBps,
      feeCollector.address,
      deployer.address
    );

    const h2 = (a: bigint, b: bigint): bigint => F.toObject(poseidon([a, b]));

    return {
      deployer, alice, recipient, relayer, feeCollector, aspOperator,
      poseidon, F, hasher, verifier, token, asp, pool, protocolFeeBps, h2,
    };
  }

  function makeNote(h2: (a: bigint, b: bigint) => bigint, value: bigint) {
    const nullifier = BigInt("0x" + "11".repeat(31)); // < field
    const secret = BigInt("0x" + "22".repeat(31));
    const precommit = h2(nullifier, secret);
    const commitment = h2(value, precommit);
    const nullifierHash = h2(nullifier, nullifier);
    return { nullifier, secret, commitment, nullifierHash };
  }

  it("deposits: inserts commitment, pulls tokens, root matches JS tree", async () => {
    const { alice, token, pool, poseidon, h2 } = await deploy();
    const value = 1_000_000_000n; // 1,000 USDC (6 dp)
    await token.mint(alice.address, value);
    await token.connect(alice).approve(await pool.getAddress(), value);

    const { commitment } = makeNote(h2, value);

    await expect(pool.connect(alice).deposit(commitment, value, "0x1234"))
      .to.emit(pool, "Deposit")
      .withArgs(commitment, 0, value, "0x1234", (t: bigint) => t > 0n);

    expect(await token.balanceOf(await pool.getAddress())).to.equal(value);
    expect(await pool.commitments(commitment)).to.equal(true);

    const expectedRoot = jsRootAfterFirstLeaf(poseidon, commitment);
    expect(await pool.getLastRoot()).to.equal(expectedRoot);
    expect(await pool.isKnownRoot(expectedRoot)).to.equal(true);
  });

  it("rejects duplicate commitments and zero value", async () => {
    const { alice, token, pool, h2 } = await deploy();
    const value = 500_000_000n;
    await token.mint(alice.address, value * 2n);
    await token.connect(alice).approve(await pool.getAddress(), value * 2n);
    const { commitment } = makeNote(h2, value);

    await pool.connect(alice).deposit(commitment, value, "0x");
    await expect(
      pool.connect(alice).deposit(commitment, value, "0x")
    ).to.be.revertedWithCustomError(pool, "CommitmentExists");

    const { commitment: c2 } = makeNote(h2, 1n);
    await expect(
      pool.connect(alice).deposit(c2, 0n, "0x")
    ).to.be.revertedWithCustomError(pool, "ValueZero");
  });

  it("withdraws privately: splits value across recipient, relayer, protocol", async () => {
    const { alice, recipient, relayer, feeCollector, token, pool, asp, aspOperator, h2 } =
      await deploy();
    const value = 1_000_000_000n;
    await token.mint(alice.address, value);
    await token.connect(alice).approve(await pool.getAddress(), value);
    const note = makeNote(h2, value);
    await pool.connect(alice).deposit(note.commitment, value, "0x");

    const root = await pool.getLastRoot();
    const aspRoot = note.commitment; // stand-in approved-set root for the mock
    await asp.connect(aspOperator).publishRoot(aspRoot, "ipfs://cid");

    const relayerFee = 2_000_000n; // 2 USDC
    const protocolFee = (value * 10n) / 10_000n; // 0.10% = 1 USDC
    const signals = [
      root,
      aspRoot,
      note.nullifierHash,
      BigInt(recipient.address),
      BigInt(relayer.address),
      relayerFee,
      value,
    ];
    const zkA: [bigint, bigint] = [0n, 0n];
    const zkB: [[bigint, bigint], [bigint, bigint]] = [[0n, 0n], [0n, 0n]];
    const zkC: [bigint, bigint] = [0n, 0n];

    await expect(pool.withdraw(zkA, zkB, zkC, signals))
      .to.emit(pool, "Withdrawal")
      .withArgs(
        note.nullifierHash,
        recipient.address,
        relayer.address,
        value - relayerFee - protocolFee,
        relayerFee,
        protocolFee
      );

    expect(await token.balanceOf(recipient.address)).to.equal(
      value - relayerFee - protocolFee
    );
    expect(await token.balanceOf(relayer.address)).to.equal(relayerFee);
    expect(await token.balanceOf(feeCollector.address)).to.equal(protocolFee);
    expect(await pool.nullifierHashUsed(note.nullifierHash)).to.equal(true);
  });

  it("prevents double-spend via nullifier", async () => {
    const { alice, recipient, relayer, token, pool, asp, aspOperator, h2 } =
      await deploy();
    const value = 400_000_000n;
    await token.mint(alice.address, value);
    await token.connect(alice).approve(await pool.getAddress(), value);
    const note = makeNote(h2, value);
    await pool.connect(alice).deposit(note.commitment, value, "0x");

    const root = await pool.getLastRoot();
    await asp.connect(aspOperator).publishRoot(note.commitment, "ipfs://cid");
    const signals = [
      root, note.commitment, note.nullifierHash,
      BigInt(recipient.address), BigInt(relayer.address), 0n, value,
    ];
    const z2: [bigint, bigint] = [0n, 0n];
    const z4: [[bigint, bigint], [bigint, bigint]] = [[0n, 0n], [0n, 0n]];

    await pool.withdraw(z2, z4, z2, signals);
    await expect(pool.withdraw(z2, z4, z2, signals)).to.be.revertedWithCustomError(
      pool,
      "NullifierUsed"
    );
  });

  it("rejects unknown pool root, unknown ASP root, and bad proofs", async () => {
    const { alice, recipient, relayer, token, pool, asp, aspOperator, verifier, h2 } =
      await deploy();
    const value = 300_000_000n;
    await token.mint(alice.address, value);
    await token.connect(alice).approve(await pool.getAddress(), value);
    const note = makeNote(h2, value);
    await pool.connect(alice).deposit(note.commitment, value, "0x");
    const root = await pool.getLastRoot();
    const z2: [bigint, bigint] = [0n, 0n];
    const z4: [[bigint, bigint], [bigint, bigint]] = [[0n, 0n], [0n, 0n]];

    // unknown pool root
    await asp.connect(aspOperator).publishRoot(note.commitment, "ipfs://cid");
    await expect(
      pool.withdraw(z2, z4, z2, [
        12345n, note.commitment, note.nullifierHash,
        BigInt(recipient.address), BigInt(relayer.address), 0n, value,
      ])
    ).to.be.revertedWithCustomError(pool, "UnknownRoot");

    // unknown ASP root
    await expect(
      pool.withdraw(z2, z4, z2, [
        root, 999n, note.nullifierHash,
        BigInt(recipient.address), BigInt(relayer.address), 0n, value,
      ])
    ).to.be.revertedWithCustomError(pool, "UnknownAspRoot");

    // rejected proof
    await verifier.setAccept(false);
    await expect(
      pool.withdraw(z2, z4, z2, [
        root, note.commitment, note.nullifierHash,
        BigInt(recipient.address), BigInt(relayer.address), 0n, value,
      ])
    ).to.be.revertedWithCustomError(pool, "InvalidProof");
  });

  it("rejects fee that exceeds value", async () => {
    const { alice, recipient, relayer, token, pool, asp, aspOperator, h2 } =
      await deploy();
    const value = 100_000_000n;
    await token.mint(alice.address, value);
    await token.connect(alice).approve(await pool.getAddress(), value);
    const note = makeNote(h2, value);
    await pool.connect(alice).deposit(note.commitment, value, "0x");
    const root = await pool.getLastRoot();
    await asp.connect(aspOperator).publishRoot(note.commitment, "ipfs://cid");
    const z2: [bigint, bigint] = [0n, 0n];
    const z4: [[bigint, bigint], [bigint, bigint]] = [[0n, 0n], [0n, 0n]];

    await expect(
      pool.withdraw(z2, z4, z2, [
        root, note.commitment, note.nullifierHash,
        BigInt(recipient.address), BigInt(relayer.address), value, value,
      ])
    ).to.be.revertedWithCustomError(pool, "FeeTooHigh");
  });

  it("association registry gates root publication to the operator", async () => {
    const { asp, aspOperator, alice } = await deploy();
    await expect(
      asp.connect(alice).publishRoot(123n, "ipfs://x")
    ).to.be.revertedWithCustomError(asp, "NotOperator");
    await asp.connect(aspOperator).publishRoot(123n, "ipfs://x");
    expect(await asp.isKnownRoot(123n)).to.equal(true);
    expect(await asp.isKnownRoot(456n)).to.equal(false);
  });
});
