// GENERATED by tools/solve.mjs — do not edit by hand.
// Move-optimal solutions for every level in levels.js.
// Lowercase = step, uppercase = push.

export const SOLUTIONS = {
  "warmup": {
    "par": 1,
    "pushes": 1,
    "moves": "R"
  },
  "corridor": {
    "par": 6,
    "pushes": 2,
    "moves": "luurDD"
  },
  "tee": {
    "par": 10,
    "pushes": 3,
    "moves": "drUluRuulD"
  },
  "pair": {
    "par": 9,
    "pushes": 4,
    "moves": "luRRRdrdL"
  },
  "vault": {
    "par": 11,
    "pushes": 4,
    "moves": "uUdrruLLdlU"
  },
  "pockets": {
    "par": 12,
    "pushes": 4,
    "moves": "uRllLdrdLrrR"
  },
  "crossing": {
    "par": 14,
    "pushes": 4,
    "moves": "luulDDrrrddrUU"
  },
  "shuffle": {
    "par": 13,
    "pushes": 5,
    "moves": "llUluRdrRurDD"
  },
  "spiral": {
    "par": 12,
    "pushes": 6,
    "moves": "luurDDDrdLLL"
  },
  "weave": {
    "par": 17,
    "pushes": 4,
    "moves": "uuululDDurrrrurDD"
  },
  "sorting": {
    "par": 18,
    "pushes": 4,
    "moves": "ulluluurDDuurrrrDD"
  },
  "corners": {
    "par": 14,
    "pushes": 8,
    "moves": "URuLLdrrRurDDD"
  },
  "quad": {
    "par": 18,
    "pushes": 8,
    "moves": "UUddlUUddrrUUddrUU"
  },
  "lockbox": {
    "par": 24,
    "pushes": 5,
    "moves": "uuuulDldRdddrrrruurruLLL"
  },
  "nook": {
    "par": 19,
    "pushes": 8,
    "moves": "luurDurDlDRRllldRRR"
  },
  "triplet": {
    "par": 21,
    "pushes": 9,
    "moves": "luurDDDuuurDDDuuurDDD"
  },
  "crate-yard": {
    "par": 23,
    "pushes": 9,
    "moves": "luulDDDuuurrDDDuuurrDDD"
  },
  "pillars": {
    "par": 27,
    "pushes": 8,
    "moves": "llluuRluurrdDDuRRdddllluRRR"
  },
  "hooks": {
    "par": 29,
    "pushes": 8,
    "moves": "rurRdrruulDrdLuuulllLdlUUluRR"
  },
  "zigzag": {
    "par": 26,
    "pushes": 10,
    "moves": "luurRRllluurRRRdDDuurUUruL"
  },
  "ladder": {
    "par": 46,
    "pushes": 9,
    "moves": "dllluluurRllddrRRuUUddddrruLrrruuuulllLdddDrdL"
  },
  "atrium": {
    "par": 38,
    "pushes": 12,
    "moves": "llluluurDDldRRdrUUdrrrruruulDDrdLLdlUU"
  },
  "gate": {
    "par": 38,
    "pushes": 17,
    "moves": "lldRRRRRurrdLdlUlluuullDDldRRRRRUrDrdL"
  },
  "finale": {
    "par": 34,
    "pushes": 12,
    "moves": "lluuuuulDDrddRdrUUdRRdrUluurUruLLL"
  }
};

export function solutionFor(levelId) {
  return SOLUTIONS[levelId] ?? null;
}
