// SPDX-License-Identifier: MIT
pragma solidity ^0.8.24;

/// @notice Poseidon(2) hasher, deployed from circomlib-generated bytecode.
/// @dev The circomlibjs `poseidonContract` produces a contract exposing this
///      signature. VEIL only needs the 2-input variant for the Merkle tree;
///      commitment / nullifier hashing happens client-side and is constrained
///      inside the withdrawal circuit.
interface IHasher {
    function poseidon(uint256[2] calldata input) external pure returns (uint256);
}
