// SPDX-License-Identifier: MIT
pragma solidity ^0.8.24;

/// @notice Groth16 verifier interface for the VEIL withdrawal circuit.
/// @dev The production verifier is generated by snarkjs from `circuits/withdraw.circom`
///      (see `MockVerifier` for the test double). Public signals are, in order:
///      [root, aspRoot, nullifierHash, recipient, relayer, fee, value].
interface IVerifier {
    function verifyProof(
        uint256[2] calldata a,
        uint256[2][2] calldata b,
        uint256[2] calldata c,
        uint256[7] calldata publicSignals
    ) external view returns (bool);
}
