#!/usr/bin/env node
/**
 * Proves every shipped Sokoban level is solvable and bakes the result into
 * `src/games/sokoban/solutions.js`:
 *
 *   - `par`      move-optimal solution length, used for the star rating
 *   - `pushes`   pushes in that solution, shown on the level card
 *   - `moves`    the solution string the Hint item reveals, three moves at a time
 *
 * Run `npm run levels` after touching `levels.js`. A level the solver cannot
 * crack fails the build rather than shipping unsolvable.
 */
import { writeFileSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import { dirname, join } from 'node:path';
import { LEVELS } from '../src/games/sokoban/levels.js';
import { parseLevel, solve } from '../src/games/sokoban/engine.js';

const here = dirname(fileURLToPath(import.meta.url));
const out = join(here, '..', 'src', 'games', 'sokoban', 'solutions.js');

const solutions = {};
const failures = [];

for (const level of LEVELS) {
  const started = Date.now();
  let parsed;
  try {
    parsed = parseLevel(level.rows);
  } catch (err) {
    failures.push(`${level.id}: ${err.message}`);
    continue;
  }

  const result = solve(parsed);
  if (!result) {
    failures.push(`${level.id}: no solution found`);
    continue;
  }

  solutions[level.id] = {
    par: result.moves.length,
    pushes: result.pushes,
    moves: result.moves,
  };

  const ms = Date.now() - started;
  console.log(
    `${level.id.padEnd(12)} par ${String(result.moves.length).padStart(3)}  ` +
      `pushes ${String(result.pushes).padStart(2)}  ` +
      `states ${String(result.states).padStart(7)}  ${ms}ms`,
  );
}

if (failures.length) {
  console.error('\nUnsolvable or malformed levels:');
  for (const f of failures) console.error(`  - ${f}`);
  process.exit(1);
}

const body = `// GENERATED by tools/solve.mjs — do not edit by hand.
// Move-optimal solutions for every level in levels.js.
// Lowercase = step, uppercase = push.

export const SOLUTIONS = ${JSON.stringify(solutions, null, 2)};

export function solutionFor(levelId) {
  return SOLUTIONS[levelId] ?? null;
}
`;

writeFileSync(out, body);
console.log(`\nWrote ${Object.keys(solutions).length} solutions to ${out}`);
